### ISSUE TITLE
AppVeyor CI Integration: For automated builds and releases.

### ISSUE THREAD

**Issue by vigneshkarthisan** [MaxXor/xRAT#86]
@MaxXor  could you please add AppVeyor integration to this repo so that people could download the latest binaries directly from GitHub without compiling in their machines. Plus, we can check  whether the code compiles without any errors. Adding deployment to GitHub releases. That's it. I have already tried AppVeyor with the copy of your repo.

AppVeyor integrates with GitHub seamlessly and automates all builds when properly configured.

**Comment by vigneshkarthisan** [comment]
@MaxXor 

I have sent my AppVeyor.yml file to facilitate easier implementation


```yaml

version: 1.0.{build}
os: Visual Studio 2014 CTP4
configuration: Debug
build:
  project: xRAT 2.sln
  parallel: true
  verbosity: detailed
artifacts:
- path: Bin
  name: binaries
deploy:
- provider: GitHub
  auth_token:
    secure: #replace with personal access token from Settings ==> Personal access token
  artifact: binaries
  draft: true

```
